---
kind: pipeline
type: exec
os: linux
arch: amd64

name: CD

steps:
- name: remove old deployed version
  failure: ignore
  commands:
    - docker stop bloGO
    - docker rm bloGO
    - docker rmi blogo
- name: deploy new docker image
  commands:
    - docker build -t blogo .
    - docker run -d --name bloGO -v $WORKINGDIR/:/bloGO/ blogo
  environment:
    WORKINGDIR:
      from_secret: workingDir
---
kind: signature
hmac: f8123e213aca3cde716bbc4ae9b9aa77246e7cb016eac566747ef8c4f62666b5

...
